# Generated by Django 5.1.7 on 2025-03-14 15:04

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_picpay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicPayUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('N', 'Normal'), ('S', 'Lojista')], default='N', max_length=100)),
                ('document', models.CharField(max_length=14, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=11, validators=[utils.validators.validate_if_value_is_positive])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fullname'],
            },
        ),
    ]
