# Generated by Django 5.1.7 on 2025-03-13 22:56

import django.core.validators
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_picpay', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, validators=[utils.validators.is_greater_than_zero]),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, validators=[utils.validators.is_greater_than_zero]),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='cnpj',
            field=models.CharField(help_text='Use only numbers', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ invalid. Use the format: 99999999000100', regex='^[0-9]{8}0001[0-9]{2}$')]),
        ),
    ]
