# Generated by Django 5.1.7 on 2025-03-14 00:41

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_picpay', '0003_alter_customer_balance_alter_shopkeeper_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, validators=[utils.validators.valid_if_value_is_positive]),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, validators=[utils.validators.valid_if_value_is_positive]),
        ),
    ]
