# Generated by Django 5.1.7 on 2025-03-13 22:56

import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_picpay', '0003_alter_customer_balance_alter_shopkeeper_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tranfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=11, validators=[utils.validators.is_greater_than_zero])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users_picpay.shopkeeper')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users_picpay.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
