# Generated by Django 5.1.7 on 2025-03-13 22:56

import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

