# Generated by Django 5.1.7 on 2025-03-14 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
        ('users_picpay', '0004_alter_customer_balance_alter_shopkeeper_balance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tranfer',
            new_name='Transfer',
        ),
    ]
