# Generated by Django 5.1.7 on 2025-03-14 15:04

import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transfers', '0001_initial'),
        ('users_picpay', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=11, validators=[utils.validators.is_greater_than_zero])),
                ('reversed_transfer', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to='users_picpay.picpayuser')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_made', to='users_picpay.picpayuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
